config/routes.rb
Tweetflick::Application.routes.draw do

match "/auth/:provider/callback" => "sessions#create"
match '/auth/failure' => 'sessions#failure'
match '/auth/check' => 'sessions#check'
match "/signout" => "sessions#destroy", :as => :signout
match '/signin' => 'sessions#new', :as => :signin
get "home/index"
get "home/about"
post "home/suggest" ,:as => 'suggest'
match "/sitemap" => "sitemap#index"
match "link/:name" => "celebs#link", :as => 'link'
match "/:name" => "celebs#profile", :as => 'profile'

root:to=>"home#index"

  resources :tweets,:only => [] do
collection do
get 'feed/:time',:action=>'feed',:as => 'feed'
get 'fanfeed/:time',:action=>'fanfeed',:as => 'fanfeed'
get 'latest/:time(/:id)',:action=>'latest',:as => 'latest'
get 'archive/:time(/:name)',:action=>'archive',:as => 'archive'
post 'retweet/:id',:action=>'retweet',:as => 'retweet'
post 'follow/:id',:action=>'follow',:as => 'follow'
post 'reply/:id',:action=>'reply',:as => 'reply'
    end
  end
  resources :celebs,:only => [:show] do
  collection do
get 'search/:name',:action=>'search',:as => 'search'
get 'list', :action => 'list', :as => 'list'
get 'feed/:id/:time',:action=>'feed',:as => 'feed'
    end
end

end

app/models/tweet.rb
class Tweet
  include Mongoid::Document

  field :text,type: String
    field :time,type: Integer

def self.keywords(array)
  array=Celeb.mostt
end
def celeb
  Celeb.first(:id=>Integer(celeb_id))
end
def self.today
  today = 0.days.ago.beginning_of_day.to_i * 1000
      where(:time.gte => today).count
end
def link_twitter_user
  @txt= self.text
  if matches = @txt.scan(/.*?(@)((?:[a-z0-9_][a-z0-9_]+))(:|\s)/i)
    matches.each do |match|
    user = match[1]
   # @txt.gsub!(user, '<a target="_blank" href="http://twitter.com/' + user + '">' + user + '</a>')
 @txt.gsub!(user, '<a  href="http://tweetflick.in/link/' + user + '">' + user + '</a>')
    end
		
	end
	@txt
end

#   Associations ::::::::::::::::::
    belongs_to:celeb
belongs_to:celebdiscussion
belongs_to:fandiscussion
    belongs_to:disctweet
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

def archive
      @date=Integer(params[:time])
          nextdate=@date+86400000
            @id=params[:id]
   unless params[:name].nil?
       @celeb = Celeb.first(conditions: {screenName: params[:name]})
     @tweets=@celeb.tweets.order_by([[:time,:desc]]).where(:time => { "$lt" => nextdate, "$gte" => @date }).only(:id,:time,:text,:celeb_id)
  else
  @tweets=Tweet.order_by([[:time,:desc]]).where(:time => { "$lt" => nextdate, "$gte" => @date }).only(:id,:time,:text,:celeb_id)
end
end

 def feed
#  @tweets=Tweet.paginate({:order => :time.desc,:per_page => 15 , :page => Integer(params[:page])})
 @tweets=Tweet.order_by([[:time,:desc]]).limit(15).where(:time.lt =>Integer(params[:time]) ).only(:id,:time,:text,:celeb_id)
respond_to do |format|
format.html {   render :partial => "celebs/feed", :locals =>{ :tweets =>  @tweets ,:url=> feed_tweets_path(:time => @tweets.to_a.last.time) } }#_list.html.erb
format.json{render json: @tweets}
end
end

def fanfeed
  
 @tweets=FanTweet.order_by([[:time,:desc]]).limit(15).where(:time.gt =>Integer(params[:time]) )

respond_to do |format|
format.html {   render :partial => "tweets/fanfeed", :locals =>{ :tweets =>  @tweets ,:url=> fanfeed_tweets_path(:time => @tweets.to_a.first.time) } }#_list.html.erb
format.json{render json: @tweets}
end
end
def latest
   unless params[:id].nil?
     celeb = Celeb.find(Integer(params[:id]))
     @tweets=celeb.tweets.order_by([[:time,:desc]]).where(:time.gt =>Integer(params[:time])).only(:id,:time,:text,:celeb_id).limit(15)
    @fantweets=FanTweet.order_by([[:time,:desc]]).where(:reply_to => celeb.screenName,:time.gt =>Integer(params[:time])).only(:id,:time,:text,:fan_id,:name,:screenName,:reply_to,:profileImgUrl).limit(5)
  else
  @tweets=Tweet.order_by([[:time,:desc]]).where(:time.gt =>Integer(params[:time])).only(:id,:time,:text,:celeb_id).limit(15)
  @fantweets=FanTweet.order_by([[:time,:desc]]).where(:time.gt =>Integer(params[:time])).only(:id,:time,:text,:fan_id,:name,:screenName,:profileImgUrl).limit(5)
end
  unless @tweets.nil? || @tweets.empty?
  celebs= render_to_string :partial => "celebs/feed", :locals =>{ :tweets =>  @tweets,:url => nil }
end
unless @fantweets.nil?
  fans=render_to_string :partial => "tweets/fanfeed", :locals =>{ :tweets =>  @fantweets }
end
  respond_to do |format|
format.json{render json: {:celebs => celebs,:fans => fans,:time => Time.now.to_i * 1000 }}
end
end
def follow
  begin
   auth = request.env["omniauth.auth"]
    unless !user_signed_in?
     # current_user.update_status(@tweet.text)
    @c = Celeb.first(conditions: {id: Integer(params[:id])}) || FanTweet.first(conditions: {fan_id: Integer(params[:id])})

      current_user.follow(Integer(params[:id]))
result={:success =>  "true", :message => "Following #{@c.name}!"}
 else
  result={:success =>  "login",:message => "Login needed !"}
 end
rescue
  result={:success =>  "false",:message => "Failed !"}
end
respond_to do |format|
format.html { redirect_to root_url }#_list.html.erb
format.js {render :json => result}
end

end

 def retweet
   begin
   auth = request.env["omniauth.auth"]
    unless !user_signed_in?
     # current_user.update_status(@tweet.text)
      current_user.retweet(Integer(params[:id]))
      result={:success =>  "true" , :message => "Retweeted!"}
 else
  result={:success =>  "login",:message => "Login needed !"}
 end
rescue
  result={:success =>  "false",:message => "Failed !"}
end
    respond_to do |format|
format.html { redirect_to root_url }
format.js {render :json => result}
end
end
def reply
   auth = request.env["omniauth.auth"]
    unless !user_signed_in?
      current_user.reply(params[:tweet],Integer(params[:id]))
result={:success =>  "true", :message => "Replied!"}
 else
  result={:success =>  "login",:message => "Login needed !"}
 end
respond_to do |format|
format.html { redirect_to root_url }#_list.html.erb
format.js {render :json => result}
end
end
end

app/helpers/tweets_helper.rb
module TweetsHelper

end

app/views/tweets/_archivelist.html.erb
<%  if !local_assigns.has_key?(:name) %>
<% name=nil %>
<%end%>
<div style="margin-top:10px">
  <b>Archives:</b> <br  />
<% start= [@date + 4 *86400000,0.days.ago.beginning_of_day.to_i * 1000].min %>
<%(0..10).each do |i| %>
<%time = start - i * 86400000  %>
<div class="archive">
<%= link_to Time.at(time/1000).strftime("%a, %b %e %Y") , archive_tweets_path(:time => time,:name => name || nil) %>
</div>
<%end%>
</div>

app/views/tweets/_fanfeed.html.erb
<% require 'rails_autolink' %>

<%  tweets.each do |tweet|%>
<% unless tweet.nil? %>
<li class="divFan divTweet ui-corner-all">
  <div class="divImg"><a target="_blank" href="http://twitter.com/<%= tweet.screenName %>"><img width="32" height="32" src="<%= tweet.profileImgUrl %>" alt="" /></a></div>
  <div class="tweetBody ui-corner-all" style="margin-left:40px;">
    <div class="divName"><%= tweet.name %></div>
    

<div><%= raw auto_link(tweet.link_twitter_user,:link =>:urls, :sanitize => false,:html => {:target => "_blank" }) %></div>
<div class="divTime">Updated <span class="epoch"><%= tweet.time %></span><span class="ltime"></span></div>
<div style="height:20px">
<div class="links right">
          <%=  link_to  image_tag("follow.png",:alt =>'follow',:width =>'18') +" follow" , follow_tweets_path(:id => tweet.fan_id),:remote=> true, :method => :post , :class=>'celeb_ajax' , 'data-type' => 'json' %> 
          <%=  link_to image_tag("retweet.png",:alt =>'retweet',:width =>'18') + " retweet" , retweet_tweets_path(:id => tweet.id),:remote=> true , :method => :post , :class=>'celeb_ajax',  'data-type' => 'json' %> 
          <a onclick="openTweetDialog(this,<%=  tweet.fan_id %>);"><%=image_tag("reply.png",:alt =>'reply',:width =>'18')%> reply</a>
  </div>
<input class="screenName" type="hidden" value="<%=tweet.screenName%>" name=""/>
</div>

</div>
<div style="clear:both"></div>

</li>
<%end%>
<%  end %>

app/views/tweets/_list.html.erb
<div id="fixedTags" class="ui-corner-all">

<div class="right">
<a href="#" id="closefixedTag"> <%=image_tag "delete_icon.png"%></a>
</div>
<div class="clr"></div>

<div>Please select tags to filter list-
</div>

<%@tags.each do |tag| %>
  <%unless tag.to_s.empty? %>
    <div class="tags"><%=  tag.to_s %></div>
    <% end %>
    <% end %>

<div style="clear:both"></div>
</div>
<div id="divLeft" class="ui-corner-right">
  <div class="scrollbar ui-corner-all">
    <div class="track ui-corner-all">
      <div class="thumb ui-corner-all">
      <div class="end ui-corner-top"></div>
    </div></div></div>
    <div class="viewport">
      <div class="overview">
        <div>
        Search <input type="" id="inpSearch" value="" name="Search" />
      </div>
      <div class="right">
      <a href="#" id="toggleTags">Filter by tags</a>
    </div>
    <div style="margin-top:20px">
      <ul class="tree">
      <%  @alphaCelebs.each do |celeb| %>
        <%  tagClass = celeb.tags.join("_tag ") + "_tag" %>
        <li>
          <div class="<%= tagClass %> alphaCeleb">
          <%= link_to celeb.name ,profile_path(:name => celeb.screenName) %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>

</div>
</div>
</div>

app/views/tweets/archive.html.erb
<%= javascript_include_tag "tweets" %>

<div id="divTabs">
<div class="divProfile">
<div class="left column1">

<b>Tweets on </b><%=Time.at(@date/1000).strftime("%a, %b %e %Y")%> <br /><br />
<%unless @tweets.empty?%>
  <%=  render :partial => "celebs/feed", :locals =>{ :tweets =>  @tweets ,:url=> feed_tweets_path(:time => @tweets.to_a.last.time) } %>
<%else%>
<div style="width:100%;margin:0 auto">
No tweets on this date.
</div>
  <%end%>
</div>
<div class="left column3">

<div class="left column2">
  <div style="color:#000;padding:10px" class="ui-corner-all">
  <span style="color:red"><%=@tweets.count %></span> total tweets on this day !  <br /> <br />
</div>
<%=  render :partial => "tweets/archivelist" %>
</div>



<div  class ="right">
<%= render :partial => "shared/googleadsense" %>
</div>
<div class="clr"></div>

</div>
<div class="clr"></div>
</div>
</div>