config/routes.rb
Tweetflick::Application.routes.draw do

match "/auth/:provider/callback" => "sessions#create"
match '/auth/failure' => 'sessions#failure'
match '/auth/check' => 'sessions#check'
match "/signout" => "sessions#destroy", :as => :signout
match '/signin' => 'sessions#new', :as => :signin
get "home/index"
get "home/about"
post "home/suggest" ,:as => 'suggest'
match "/sitemap" => "sitemap#index"
match "link/:name" => "celebs#link", :as => 'link'
match "/:name" => "celebs#profile", :as => 'profile'

root:to=>"home#index"

  resources :tweets,:only => [] do
collection do
get 'feed/:time',:action=>'feed',:as => 'feed'
get 'fanfeed/:time',:action=>'fanfeed',:as => 'fanfeed'
get 'latest/:time(/:id)',:action=>'latest',:as => 'latest'
get 'archive/:time(/:name)',:action=>'archive',:as => 'archive'
post 'retweet/:id',:action=>'retweet',:as => 'retweet'
post 'follow/:id',:action=>'follow',:as => 'follow'
post 'reply/:id',:action=>'reply',:as => 'reply'
    end
  end
  resources :celebs,:only => [:show] do
  collection do
get 'search/:name',:action=>'search',:as => 'search'
get 'list', :action => 'list', :as => 'list'
get 'feed/:id/:time',:action=>'feed',:as => 'feed'
    end
end

end

app/models/celeb.rb
class Celeb
  include Mongoid::Document
field :_id ,type: Integer
field :followers,type: Integer
field :friends,type: Integer
field :mentions,type: Integer
field :tags ,type: Array
field :screenName,type: String
field :name,type: String

def twitterlink
  img = "<img src=\"/assets/twitter-icon.png\" width=\"25\" height=\"25\" />"
  "<a target=\"_blank\" href=\"http://twitter.com/#{self.screenName}\" class=\"right\"> <span style=\"color:#369;font-size:11px;\">View on twitter</span> &nbsp; </a>"
end
def title_page
  "#{self.name} on Twitter - #{self.name} Twitter ID - #{self.name} Tweets & Messages - Tweetflick.in"
end
def meta_keywords
    "#{self.name} twitter , #{self.name} twitter , #{self.name} fans, #{self.name} images , #{self.name} internet, #{self.name} personal , #{self.name} bollywood, #{self.name} tollywood, #{self.name} kollywood, #{self.name} analytics, #{self.name} tweets, #{self.name} retweets, #{self.name} follow"
end
def meta_description
   " Real time Twitter feed, Analytics of  #{self.name} on Twitter. Follow , retweet, reply, see discussions , view image gallery , comment  of  #{self.name}."
end
def large
#self.profileImgUrl.gsub!(/_([a-z0-9-]+).(png|gif|jpg|jpeg|JPG|JPEG|GIF|PNG)/, '.\2')
self.profileImgUrl.gsub!(/_normal\.(?=png|gif|jpg|jpeg|tiff|TIFF|bmp|JPG|JPEG|GIF|PNG|BMP +\z)/,'.\2')
end
def bigger
#self.profileImgUrl.gsub!(/_([a-z0-9-]+).(png|gif|jpg|jpeg|JPG|JPEG|GIF|PNG)/, '.\2')
self.profileImgUrl.gsub!(/_normal\.(?=png|gif|jpg|jpeg|tiff|TIFF|bmp|JPG|JPEG|GIF|PNG|BMP +\z)/,'_bigger.\2')
end
def self.random
       # Grabs a random entry from the MongoDB Entry.
       # Returns an array
 Celeb.skip(rand(Celeb.count)).first
end

def self.weekstats
keyf = <<KEYF
 function(doc) {
var weekday=new Array("Sun","Mon","Tue","Wed","Thu",
                "Fri","Sat")

              //  a=new Date(doc.time+475200);
                a=new Date(doc.time);
                a.setHours(0);
                a.setMinutes(0);
                a.setSeconds(0);
                a.setMilliseconds(0);
return {"day" : weekday[a.getDay()],"epoch":a.getTime()  }

 }
KEYF
sixdays = 6.days.ago.to_i * 1000
#sixdays = 6.days.ago.to_i * 1000
cond = {:time => {'$gte' => sixdays }}
reduce = <<REDUCE
  function(key,values){
values.tweets+=1;
}
REDUCE
array=Tweet.collection.group( {:keyf => keyf,:cond => cond ,:initial => {tweets:0},:reduce => reduce})
array.sort {|a,b| a["epoch"] <=> b["epoch"]}
end
def self.featured
  begin
  id= Celeb.db["featured"].find_one()['_id']
Celeb.find(id)
rescue 
  Celeb.random
end
end
def self.mosttweetstoday
keyf = <<KEYF
function(doc) {
celeb=db.celebs.findOne({_id : doc.celeb_id})
return {"celeb" : celeb }
 }
KEYF
today = 0.days.ago.beginning_of_day.to_i * 1000
#today = 1.days.ago.to_i * 1000
cond = {:time => {'$gte' => today }}
reduce = <<REDUCE
  function(key,values){
values.tweets+=1;
}
REDUCE

array=Tweet.collection.group( {:keyf => keyf,:cond => cond ,:initial => {tweets:0},:reduce => reduce}).delete_if {|doc| doc["celeb"].nil?}
array.sort {|a,b| b["tweets"] <=> a ["tweets"]}
end
def self.mostmentionedtoday
keyf = <<KEYF
function(doc) {
celeb=db.celebs.findOne({screenName : doc.reply_to})
return {"celeb" : celeb }
 }
KEYF
#today = 1.days.ago.to_i * 1000
today = 0.days.ago.beginning_of_day.to_i * 1000
cond = {:time => {'$gte' => today }}
reduce = <<REDUCE
  function(key,values){
values.tweets+=1;
}
REDUCE
  array=FanTweet.collection.group( {:keyf => keyf,:cond => cond ,:initial => {tweets:0},:reduce => reduce}).delete_if {|doc| doc["celeb"].nil?}
array.sort {|a,b| b["tweets"] <=> a ["tweets"]}
end


  def self.alltags
     tags = Mongoid.master.collection('tags').find().first["value"]["tags"].split(/,/).to_a.uniq
  end
  def self.rebuild_tags
    map = <<MAP
      function() {
          emit({}, {tags: this.tags})
        }
MAP

    reduce = <<REDUCE
    function(key, values) {
       var arr=new Array
 values.forEach(function(doc){
 arr=arr+","+doc.tags
 })
 return {tags:arr};
 }
REDUCE

    collection.mapreduce(map, reduce,{:out => "tags"})

  end
has_many :tweets do
  def today
  #  today = 1.days.ago.to_i * 1000
  today = 0.days.ago.beginning_of_day.to_i * 1000
    where(:time.gte => today).count
  end

end
end

app/controllers/celebs_controller.rb
class CelebsController < ApplicationController
  # GET /celebs
  # GET /celebs.json
  def index
    @celebs = Celeb.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @celebs }
    end
  end

def link
  begin
       
  @celeb = Celeb.first(conditions: {screenName: params[:name]})
#          @alphaCelebs=Celeb.order_by([[:name]])
#   @tags=Celeb.alltags
    unless @celeb.nil?
      redirect_to profile_path(:name => @celeb.screenName)
    else
      redirect_to 'http://twitter.com/'+params[:name]
    end
rescue Exception => e
  redirect_to root_url
end
end
def profile
  begin
       
  @celeb = Celeb.first(conditions: {screenName: params[:name]})
#          @alphaCelebs=Celeb.order_by([[:name]])
#   @tags=Celeb.alltags
    @date = 0.days.ago.beginning_of_day.to_i * 1000
    @tweets=@celeb.tweets.order_by([[:time,:desc]]).only(:id,:time,:text,:celeb_id).limit(15)
    @fantweets=FanTweet.where(:reply_to => @celeb.screenName).order_by([[:time,:desc]]).only(:id,:time,:text,:fan_id,:name,:screenName,:reply_to,:profileImgUrl).limit(30) 
    images=Photo.where(:screenName => @celeb.screenName).order_by([[:time,:desc]]).limit(30)
    @imageStr=Array.new
  unless images.empty?
    images.each do |image|

    @imageStr <<  "<li><a target=\"_blank\" href=\"#{image.url}\"><img width=\"84\" height=\"60\" src=\"#{image.small}\"/></a><div class=\"divTime\"><span class=\"epoch\">#{image.time}</span><span class=\"ltime\">#{image.time}</span></div></li>"
    end
  end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @celeb }
    end
rescue Exception => e
  redirect_to root_url
end
end
  # GET /celebs/1
  # GET /celebs/1.json
  def show
    @celeb = Celeb.find(Integer(params[:id]))
redirect_to profile_path(:name => @celeb.screenName)
     end
 def feed
   @celeb = Celeb.find(Integer(params[:id]))
    @tweets=@celeb.tweets.order_by([[:time,:desc]]).limit(15).where(:time.lt =>Integer(params[:time]) ).only(:id,:time,:text,:celeb_id)
  
respond_to do |format|
format.html {   render :partial => "celebs/feed", :locals =>{ :tweets =>  @tweets ,:url=> feed_celebs_path(:time => @tweets.to_a.last.time) } }#_list.html.erb
format.json{render json: @tweets}
end
end
def list
  @tags=Celeb.alltags
  @alphaCelebs=Celeb.order_by([[:name]])
  respond_to do |format|
    format.html
    format.json {render json: @alphaCelebs}
  end
end  
def search
  query= Regexp.new(params[:name],true)
@celebs =Celeb.find(:all, :conditions => {:name => query }).only(:name,:screenName,:profileImgUrl).limit(15)
respond_to do |format|
  format.html
  format.json{render json: @celebs}
end
end

end

app/helpers/celebs_helper.rb
module CelebsHelper
end

app/views/celebs/_dash.html.erb
<div id="vertTabs" class="left ui-corner-all">
<ul id="divCycle">

  <li id="divFeatured" class="dash ui-corner-all">
                <div class="dashBody">
    <a class="left" href="<%= url_for :controller =>"celebs", :action => "profile", :name => @featured.screenName %>"><img width="130" height="145"  src="<%= @featured.large %>" alt=""/></a>
<div style="margin-left : 200px"><b>Featured celeb of the day- </b> <br /><br /><br />
   <a style="font-size:20px" href="<%= url_for :controller =>"celebs", :action => "profile", :name => @featured.screenName %>">
    <%= @featured.name %>
  </a>
 <br /> <br /><br /><%= @featured.followers %> - followers
</div>

<div class="clr"></div>               
</div>   
</li>

  <li id="divFollowed" class="dash ui-corner-all" >

<div style="margin-left : 200px"><b>Celebs who are followed the most </b></div><br />
                <div class="dashBody">

<%  @followCelebs.each do |celeb| %>


   <div class="left mright">
    <a href="<%= url_for :controller =>"celebs", :action => "profile", :name => celeb.screenName %>"><img  src="<%= celeb.bigger %>" alt=""/></a>
    
    
    <br />
  <a href="<%= url_for :controller =>"celebs", :action => "profile", :name => celeb.screenName %>">
    <%= celeb.name %>
  </a><br />
     <%= celeb.followers %> 
</div>

  <% end %>
<div class="clr"></div>              
              </div>
                </li>
               
<li id="divTalkative" class="dash ui-corner-all">
<div style="margin-left : 200px"><b>Celebs who were replied the most today </b></div><br /> 
                  <div class="dashBody">
<%  @mentionCelebs[0..4].each do |celeb| %>
  <% unless celeb["celeb"].nil? %>

   <div class="left mright">

 <a href="<%= url_for :controller =>"celebs", :action => "profile", :name => celeb["celeb"]["screenName"] %>">
    <img  src="<%= bigger(celeb["celeb"]["profileImgUrl"]) %>" alt=""/>
</a>
<br />
   <a href="<%= url_for :controller =>"celebs", :action => "profile", :name => celeb["celeb"]["screenName"] %>">
  <%= celeb["celeb"]["name"] %>
</a><br />
    <%= celeb["tweets"].to_i %> - mentions

</div>
  <% end %>
  <% end %>
<div class="clr"></div>
            </div>
            </li>


<li id="divMentioned" class="dash ui-corner-all">

<div style="margin-left : 200px"><b>Celebs who shared the most tweets today  </b></div><br />
                <div class="dashBody">
     
<%  @talkCelebs[0..4].each do |celeb| %>

   <div class="left mright">
   <a href="<%= url_for :controller =>"celebs", :action => "profile", :name => celeb["celeb"]["screenName"] %>">
<img  src="<%= bigger(celeb["celeb"]["profileImgUrl"]) %>" alt=""/>
</a>
<br />
<a href="<%= url_for :controller =>"celebs", :action => "profile", :name => celeb["celeb"]["screenName"] %>">
  <%= celeb["celeb"]["name"] %>
</a><br />
<%= celeb["tweets"].to_i %> - tweets

</div>


  <% end %>
<div class="clr"></div>
                </div>
                </li>

                  
</ul> 

</div>
<div class="right ui-corner-all">
  <span style="margin:5px 5px;font-weight:bold;">No of tweets over the last 6 days : </span> <br />
      <div id="divChartStats"></div>
      <input id="hdnweekstats"  type="hidden" value="<%= @weekstats.to_json %>"/>
      <input id="hdnfanweekstats"  type="hidden" value=""/>
</div>

<div class="clr"></div>

app/views/celebs/_feed.html.erb
<% require 'rails_autolink' %>
<%  tweets.each do |tweet|%>
<% unless tweet.celeb.nil? %>
<div class="divCeleb divTweet ui-corner-all">
  <div class="divImg">

    <a  href="<%= url_for :controller =>"celebs", :action => "profile", :name => tweet.celeb.screenName %>"><img width="32" height="32" src="<%= tweet.celeb.profileImgUrl %>" alt="<%= tweet.celeb.name %>"/></a></div>
  <div class="tweetBody ui-corner-all" style="margin-left:40px;">
    <div class="divName">
     <a href="<%= url_for :controller =>"celebs", :action => "profile", :name => tweet.celeb.screenName %>">
    <%= tweet.celeb.name %>
  </a>
</div>
<div><%= raw auto_link(tweet.link_twitter_user,:link =>:urls, :sanitize => false ,:html => { :target => '_blank' }) %></div>
<div class="divTime">Updated <span class="epoch"><%= tweet.time %></span><span class="ltime"></span></div>
<div style="height:18px">
    <div class="links right">
     <%=  link_to image_tag("follow.png",:alt =>'follow',:width =>'18') +" follow" , follow_tweets_path(:id => tweet.celeb.id),:remote=> true, :method => :post , :class=>'celeb_ajax' , :title => 'retweet','data-type' => 'json' %> 
          <%=  link_to image_tag("retweet.png",:alt =>'retweet',:width =>'18') + " retweet", retweet_tweets_path(:id => tweet.id),:remote=> true , :method => :post , :class=>'celeb_ajax', :title => 'retweet', 'data-type' => 'json' %> 
          <a onclick="openTweetDialog(this,<%=  tweet.celeb.id %>);" title="reply"><%=image_tag("reply.png",:alt =>'reply',:width =>'18')%> reply</a>
  </div>
<input type="hidden" class="screenName" value="<%=tweet.celeb.screenName%>" name=""/>
</div>

</div>
<div style="clear:both"></div>

</div>
<%end%>
<%  end %>
            <input class="hdnPath" type="hidden" value="<%= url %>" name="hiddenPath" />
<script type="text/javascript">
$(function(){
    showDate();
  });
</script>

app/views/celebs/_form.html.erb
<%= form_for(@celeb) do |f| %>
  <% if @celeb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@celeb.errors.count, "error") %> prohibited this celeb from being saved:</h2>

      <ul>
      <% @celeb.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/celebs/edit.html.erb
<h1>Editing celeb</h1>

<%= render 'form' %>

<%= link_to 'Show', @celeb %> |
<%= link_to 'Back', celebs_path %>

app/views/celebs/index.html.erb
<h1>Listing celebs</h1>
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @celebs.each do |celeb| %>
  <tr>
    <td><%= link_to 'Show', celeb %></td>
    <td><%= link_to 'Edit', edit_celeb_path(celeb) %></td>
    <td><%= link_to 'Destroy', celeb, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Celeb', new_celeb_path %>

app/views/celebs/list.html.erb
<%= javascript_include_tag "list" %>
<%title 'Celebrity search page at tweetflick.in'%>
<%set_meta( :keywords => "twitter celebrities , twitter fans, celeb tweets, celebrity tweets,bollywood tweets,tollywood tweets,tolly  tweets,bolly tweets,bolly pics,tolly pictures,bolly pictures,tolly pictures , celebrity analytics , fan discussions, indian movie stars , movie stars on twitter , bollywood social media" , :description => " Search for your favourite celeb at tweetflick.in")%>

<div style="width:120px;margin-top:60px" class="left">
<b>Filter by tags : </b> <br /> <br />
<%@tags.each do |tag| %>
  <%unless tag.to_s.empty? %>
    <div class="tags"><%=  tag.to_s %></div>
    <% end %>
    <% end %>
    <a id="clearTags" style="cursor:pointer;color:#369" class="right">Clear All</a>
</div>
<div class="left" style="width:670px;border:1px solid #ddd;">
 <%= render :partial => 'shared/social' %>
<br /><br />     &nbsp;Quick Search &nbsp; <input type="" id="inpSearch" value="" name="Search" /><br /><br />
      <%  @alphaCelebs.each do |celeb| %>
        <%  tagClass = celeb.tags.join("_tag ") + "_tag" %>
          <div class="<%= tagClass %> left listCeleb" align="left">
          <%= link_to image_tag(celeb.profileImgUrl, :width => '32',:height => '32') ,profile_path(:name => celeb.screenName) %>
          <%= link_to celeb.name ,profile_path(:name => celeb.screenName) %>
        </div>
      
      <% end %>
  </div>
<div class="right">
  <%= render :partial => "shared/googleadsense" %>
</div>
<div class="clr"></div>

app/views/celebs/new.html.erb
<h1>New celeb</h1>

<%= render 'form' %>

<%= link_to 'Back', celebs_path %>

app/views/celebs/profile.html.erb
  <%= javascript_include_tag "celebs" %>
    <%ogtitle "#{@celeb.name}'s home page -TweetFlick.in" %>
  <%title @celeb.title_page %>
    <%ogimage @celeb.profileImgUrl %>
 <%set_meta( :keywords => @celeb.meta_keywords,:description => @celeb.meta_description)%>

   <div id="divTabs">
<div class="divProfile">
    

  <div class="pf_divImg">
<a href="<%= url_for :controller =>"celebs", :action => "profile", :name => @celeb.screenName %>">      
<img src="<%= @celeb.large %>" width="120" height="140"/> 
</a>&nbsp;
</div>

<div class="pf_description ui-corner-all">
<%=raw @celeb.twitterlink %> 
<%unless @celeb.description.empty? %>
<b>Description</b> <br /><br />
<p><%= @celeb.description %></p><br />
<%else %>
<br /> <br />
<%end%>
</div>

    <div class="pf_profile-content">
      <h2 class="divName">
<a href="<%= url_for :controller =>"celebs", :action => "profile", :name => @celeb.screenName %>">      
<%= @celeb.name %>
</a> &nbsp;
<%if @celeb.isVerified==1 %>
<%=image_tag "verified.png" %>
<%end%>
</h2>
<%unless @celeb.location.empty? %>
<div style="margin:2px">

<span style="color:#2F7A26;">Location : </span><%= @celeb.location %>

</div>
<%end%>
<br />
      <div><span style="color:#2F7A26;">Tags: </span>
    <%@celeb.tags.each do |tag| %>
        <i><%=  tag.to_s %></i>
        <% end %>
      
      </div> <br />
 <div "padding:3px">
<span style="color:#2F7A26;">Followers : </span> <%= @celeb.followers %> &nbsp;&nbsp;
<span style="color:#2F7A26;">Friends : </span><%= @celeb.friends %>    &nbsp;&nbsp;
<span style="color:#2F7A26;">Statuses : </span><%= @celeb.statuses %>    &nbsp;&nbsp;
    </div><br /><br />
<div> <span style="color:#2F7A26;"><%=@celeb.tweets.today %></span> - tweets today !  &nbsp;&nbsp;    
<span style="color:#2F7A26;"> <%= FanTweet.todayby(@celeb.screenName) %></span>  mentions today !
</div>
    <div class="clr"></div>
      </div> <br />
      <div style="clear:both"></div>
<%= render :partial => 'shared/social' %>
<table cellspacing="0"><tr>
<td style="width:450px"><b style="float:left">Recent Tweets:</b> </td>
<td><b id="noteImage" style="margin-left:10px;float:left">Recent Images:</b> </td>
</tr></table>
  <div class="left column1">
<%unless @tweets.empty? %>
    <%=  render :partial => "celebs/feed", :locals =>{ :tweets =>  @tweets ,:url=> feed_celebs_path(@celeb,:time => @tweets.to_a.last.time)} %>
<%else%>
<div style="width:100%;margin:0 auto">
No tweets on this date.
</div>
<%end%>
            </div>
          <div class="left column3">

            <div>
              <input id="hdnImages" type="hidden" value="<%=  @imageStr.to_json %>" />
          <ul class="ulGallery jcarousel-skin-tango">
           
          </ul>
          
          </div> <br />
  <div class="left column2">
    
    <div>
      
      <% unless @fantweets.nil? || @fantweets.empty? %>
      <span style="color:#000;font-weight:bold"> Recent Fan Replies :</span>  <br />
      <ul class="divScrollable jcarousel-skin-fan">
        <%=  render :partial => "tweets/fanfeed", :locals =>{ :tweets =>  @fantweets ,:url=> fanfeed_tweets_path(:time => @fantweets.to_a.last.time) } %>
      </ul>
<% else %>
<div style="height:700px;border:1px solid #ddd;" align="center"> No recent tweets found. </div>
      <% end %>
    </div>
        <input class="hdnLtstTime" value="<%= Time.now.to_i * 1000 %>" type="hidden" name="" />
            <input class="hdnprofile" value="<%= @celeb.id %>" type="hidden" name="" />
  </div>
     <div  class ="right">
       <%= render :partial => "shared/googleadsense" %>
    </div>
  <div class="clr"></div>
   <br />            
<span id="noteImage" style="color:#000;font-weight:bold;display:none"> Say something about <%=@celeb.name %> : <br /></span> 
<%=  render :partial => "shared/fb" %>
</div>
  <div class="clr"></div>
</div>
</div>

app/views/celebs/show.html.erb
<div class="divProfile">

 <div class="divImg">
<a target="_blank" href="<%= url_for :controller =>"celebs", :action => "profile", :name => @celeb.screenName %>">
<img src="<%= @celeb.profileImgUrl %>" alt=""/> 
</a>
</div> 
  <%=  link_to "View complete profile" , profile_path(:name => @celeb.screenName), :class=>'right',:target => "_blank" %>
  <div class="profile-content">
      <h2 class="divName">
<a target="_blank" href="<%= url_for :controller =>"celebs", :action => "profile", :name => @celeb.screenName %>">      
    <%= @celeb.name %>
</a>
</h2>
      <div><span style="color:#2F7A26;">Tags:
    <%@celeb.tags.each do |tag| %>
        <i><%=  tag.to_s %></i>
        <% end %>
      </span>
      </div> <br />
 <div "padding:5px">
<span style="color:red"><%= @celeb.followers %> </span> - followers  &nbsp;&nbsp;
 <span style="color:red"><%=@celeb.tweets.today %></span> - tweets today !  &nbsp;&nbsp;    
<span style="color:red"> <%= FanTweet.todayby(@celeb.screenName) %></span>  mentions today !
    </div>
<br />
      </div>
      <div style="clear:both"></div>
  
  
<div class="left column1">
  <%unless @tweets.empty? %>
  <%=  render :partial => "celebs/feed", :locals =>{ :tweets =>  @tweets ,:url=> feed_celebs_path(@celeb,:time => @tweets.to_a.last.time)} %>
<%else%>
<div style="width:100%;margin:0 auto">
No tweets on this date.
</div>
<%end%>
</div>
<div class="left column3">
  <div class="left column2">
    <div>
      
      <% unless @fantweets.nil? || @fantweets.empty? %>
      <span style="color:#2F7A26;font-weight:bold"> Recent Fan Replies :</span>  <br />
      <ul class="divScrollable jcarousel-skin-fan">
        <%=  render :partial => "tweets/fanfeed", :locals =>{ :tweets =>  @fantweets ,:url=> fanfeed_tweets_path(:time => @fantweets.to_a.last.time) } %>
      </ul>
      <% end %>
    </div>
                <input class="hdnprofile" value="<%= @celeb.id %>" type="hidden" name="" />
    <input class="hdnLtstTime" value="<%= Time.now.to_i * 1000 %>" type="hidden" name="" />
  </div>
  <div class="clr"></div>
</div>
  <div class="clr"></div>
</div>