config/routes.rb
Tweetflick::Application.routes.draw do

match "/auth/:provider/callback" => "sessions#create"
match '/auth/failure' => 'sessions#failure'
match '/auth/check' => 'sessions#check'
match "/signout" => "sessions#destroy", :as => :signout
match '/signin' => 'sessions#new', :as => :signin
get "home/index"
get "home/about"
post "home/suggest" ,:as => 'suggest'
match "/sitemap" => "sitemap#index"
match "link/:name" => "celebs#link", :as => 'link'
match "/:name" => "celebs#profile", :as => 'profile'

root:to=>"home#index"

  resources :tweets,:only => [] do
collection do
get 'feed/:time',:action=>'feed',:as => 'feed'
get 'fanfeed/:time',:action=>'fanfeed',:as => 'fanfeed'
get 'latest/:time(/:id)',:action=>'latest',:as => 'latest'
get 'archive/:time(/:name)',:action=>'archive',:as => 'archive'
post 'retweet/:id',:action=>'retweet',:as => 'retweet'
post 'follow/:id',:action=>'follow',:as => 'follow'
post 'reply/:id',:action=>'reply',:as => 'reply'
    end
  end
  resources :celebs,:only => [:show] do
  collection do
get 'search/:name',:action=>'search',:as => 'search'
get 'list', :action => 'list', :as => 'list'
get 'feed/:id/:time',:action=>'feed',:as => 'feed'
    end
end

end

app/views/shared/_dialog.html.erb
<div id="dialog-tweet" class="popDialog" style="display:none">

<div style="zoom:1;clear:both"> 

<label>Whats on your mind:</label>
<span id="spnChars" style="float:right">140</span>
 </div>
<br />
 <div> <textarea  name="tweet" id="tweet" class="text ui-corner-all" ></textarea></div>
<br />

<div id="tweetControls" style="text-align:right">
<span><button type="button" id="btnTweet">Tweet</button> &nbsp;
<button type="button" class="btnClose">Cancel</button>
</span>
</div>

</div>
<div id="suggestbox" class="popDialog" style="display:none">
<%= form_tag('/home/suggest',:remote => true,'data-type' => 'json',:class=>'form_ajax celeb_ajax') do %>
<table>
<tr>
<td>Celeb name : </td> <td>  <%= text_field_tag(:cname ,'', :class => 'required') %> </td>
</tr>
<tr><td>Twitter Id : </td> <td> <%= text_field_tag(:cid) %></td></tr>
<tr><td>Email :  </td> <td> <%= email_field_tag(:cemail) %> </td></tr>
<tr><td>Comments : </td> <td><%= text_area_tag(:comments) %></td></tr>
</table>
<div style="text-align:right">
  <%= submit_tag 'Submit'  %>
<button type="button" class="btnClose">Cancel</button>
</div>
<% end %>
</div>

<div class="TranslucentBackgroundForPopUp" style="display: none">
    </div>

app/views/shared/_fb.html.erb
<% if Rails.env.production? %>
<div style="margin-top:10px">

<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:comments href="http://www.tweetflick.in/" num_posts="5" width="450"></fb:comments>
</div>
<%end%>

app/views/shared/_googleadsense.html.erb
<% if Rails.env.production? %>
<script type="text/javascript"><!--
google_ad_client = "ca-pub-7459561568356572";
/* tweetflick */
google_ad_slot = "5788773018";
google_ad_width = 160;
google_ad_height = 600;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<%else%>
<%= image_tag "160x600.gif" %>
<%end%>

app/views/shared/_googleanalytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25319183-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
  <%unless current_user.image.nil? %>
   <div class="divImg">

     <img width="32" height="32" src="<%= current_user.image %>" alt="" style="border:none !important;box-shadow:none"/>

   </div>
<%end %>
<div style="margin-left:40px;margin-top:5px">
  <div style="font-weight:bold;color:black"><%= current_user.name %></div>
    <div> <%= link_to('Logout', signout_path) %> </div>
    

</div>
 
            <% else %>
        <div style="margin-top:5px;">         <%= link_to(image_tag('sign-in-with-twitter.png'), signin_path)  %>  </div>

                  <% end %>
        

app/views/shared/_social.html.erb
<% if Rails.env.production? %>
<div class="socialContainer">


<div id="divgplus" class="social">
<!-- Place this tag where you want the +1 button to render -->
<g:plusone size="medium"></g:plusone>

<!-- Place this render call where appropriate -->
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
</div>
<div class="social">
<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=196430660424884&amp;xfbml=1"></script><fb:like href="" send="false" layout="button_count" show_faces="true" font="lucida grande"></fb:like>
</div>
<div class="social">

<!--Twitter ( from http://twitter.com/about/resources/tweetbutton): -->
<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="tweetflick_in">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
</div>
<div class="clr"></div>
</div>
<div class="clr"></div>
<% end %>