config/routes.rb
Tweetflick::Application.routes.draw do

match "/auth/:provider/callback" => "sessions#create"
match '/auth/failure' => 'sessions#failure'
match '/auth/check' => 'sessions#check'
match "/signout" => "sessions#destroy", :as => :signout
match '/signin' => 'sessions#new', :as => :signin
get "home/index"
get "home/about"
post "home/suggest" ,:as => 'suggest'
match "/sitemap" => "sitemap#index"
match "link/:name" => "celebs#link", :as => 'link'
match "/:name" => "celebs#profile", :as => 'profile'

root:to=>"home#index"

  resources :tweets,:only => [] do
collection do
get 'feed/:time',:action=>'feed',:as => 'feed'
get 'fanfeed/:time',:action=>'fanfeed',:as => 'fanfeed'
get 'latest/:time(/:id)',:action=>'latest',:as => 'latest'
get 'archive/:time(/:name)',:action=>'archive',:as => 'archive'
post 'retweet/:id',:action=>'retweet',:as => 'retweet'
post 'follow/:id',:action=>'follow',:as => 'follow'
post 'reply/:id',:action=>'reply',:as => 'reply'
    end
  end
  resources :celebs,:only => [:show] do
  collection do
get 'search/:name',:action=>'search',:as => 'search'
get 'list', :action => 'list', :as => 'list'
get 'feed/:id/:time',:action=>'feed',:as => 'feed'
    end
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

 #@alphaCelebs=Celeb.order_by([[:name]])
    @tweets=Tweet.order_by([[:time,:desc]]).only(:id,:time,:text,:celeb_id).limit(15)
        @fantweets=FanTweet.order_by([[:time,:desc]]).only(:id,:time,:text,:fan_id,:reply_to,:name,:screenName,:profileImgUrl).limit(30)
@followCelebs=Celeb.order_by([[:followers,:desc]]).only(:name,:screenName,:profileImgUrl,:followers).limit(5)
images=Photo.order_by([[:time,:desc]]).limit(30)
@imageStr=Array.new
images.each do |image|
urlstr=  url_for :controller =>"celebs", :action => "profile", :name => image.screenName
@imageStr <<  "<li style=\"overflow:hidden\"><a target=\"_blank\" href=\"#{urlstr}\"><span style=\"white-space:nowrap\">#{image.name}</span></a><a target=\"_blank\" href=\"#{image.url}\"><img width=\"84\" height=\"60\" src=\"#{image.small}\"/></a><div class=\"divTime\"><span class=\"epoch\">#{image.time}</span><span class=\"ltime\">#{image.time}</span></div></li>"
end
@mentionCelebs=Celeb.mostmentionedtoday
@talkCelebs=Celeb.mosttweetstoday
@weekstats=Celeb.weekstats
#@fanweekstats=FanTweet.weekstats
#@featured=Celeb.random
 @featured=Celeb.featured
#@tags=Celeb.alltags
@tmstamp=@tweets.to_a.last.time
@date = 0.days.ago.beginning_of_day.to_i * 1000

respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @celebs }
      format.js
    end
    
    end

def suggest
  begin
   auth = request.env["omniauth.auth"]
    unless !user_signed_in?
     # current_user.update_status(@tweet.text)
  #  @c = Celeb.first(conditions: {id: Integer(params[:id])}) || FanTweet.first(conditions: {fan_id: Integer(params[:id])})
debugger
suggest= Suggest.new

suggest.name = params[:cname]
suggest.userName = params[:cid]
suggest.email = params[:cemail]
suggest.comments = params[:comments]
suggest.save
result={:success =>  "true", :message => "Thank you."}
 else
  result={:success =>  "login",:message => "Login needed !"}
 end
rescue
  result={:success =>  "false",:message => "Failed !"}
end
respond_to do |format|
format.html { redirect_to root_url }#_list.html.erb
format.js {render :json => result}
end
end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div id="about" class="ui-corner-all"> 
<p  style="padding:40px 60px;height:200px;" align="justify">
<span style="font-weight:bold; color:#336699;">TweetFlick</span> is a one stop place to follow all your favourite indian movie celebrities.<br/> Twitter is one and only online platform where most of the stars from bollywood, south indian movies engage with their fans. We gather them at one place, divide into categories, provide basic analytics on your favourite stars online activity.<br /> With TweetFlick, you get upto minute real time feed of the tweets, fan replies, conversations between celebrities and also celebrity-fan interactions. <br />TweetFlick aims to provide genuine information based on verified celebrities.  
You can follow,reply and retweet to all the celebs from here. <br />
 Apart from everything else TweetFlick is simple and usable.

<br /><br /><span style=""> Contact us at &nbsp; &nbsp; <a href="mailto:admin@tweetflick.in" >admin@tweetflick.in</a> . <br/>
Please provide your feedback at <a href="mailto:feedback@tweetflick.in" >feedback@tweetflick.in</a></span> <br />

</p> <br /><br /><br />

<div style="margin-left:20px">
 &nbsp;&nbsp;&nbsp;&nbsp;<%=image_tag "PBAWS_LOGO_127px.JPG",:style=> 'position:relative;margin-bottom:5px;' %> &nbsp;&nbsp;&nbsp;&nbsp;
<%=image_tag "PoweredMongoDBblue50.png"%> 

</div>


</div>

app/views/home/index.html.erb
<%= javascript_include_tag "home" %>
<%ogtitle "Tweetflick.in -Home page"%>
<%set_meta( :keywords => "twitter celebrities , twitter fans, celeb tweets, celebrity tweets,bollywood tweets,tollywood tweets,tolly  tweets,bolly tweets,bolly pics,tolly pictures,bolly pictures,tolly pictures , celebrity analytics , fan discussions, indian movie stars , movie stars on twitter , bollywood social media" , :description => " Real time Twitter feed, Analytics of Indian movie celebrities on Twitter. Follow , retweet, reply, see their discussions , view image gallery , comment on them and lot more.")%>



<div id="divDashBoard">
<%= render :partial => "celebs/dash" %>
<div class="clr"></div>
</div>
<%= render :partial => 'shared/social' %>

<div id="divContent">

<div id="divTabs">
  <div  class ="gadsense">
  <%= render :partial => "shared/googleadsense" %>
</div>
<table cellspacing="0"><tr>
<td style="width:450px"><b style="float:left">Recent Tweets:</b> </td>
<td><b style="margin-left:10px;float:left">Recent Images:</b> </td>
</tr></table>
<div id="divFeed">

  <div class="clr left column1">
<%unless @tweets.empty? %>
  <%=  render :partial => "celebs/feed", :locals =>{ :tweets =>  @tweets ,:url=> feed_tweets_path(:time => @tweets.to_a.last.time) } %>
<%else%>
<div style="width:100%;margin:0 auto">
No tweets on this date.
</div>
<%end%>
</div>
<div class="left column3">
  <div>
  <input id="hdnImages" type="hidden" value="<%=  @imageStr.to_json %>" />
  <ul class="ulGallery jcarousel-skin-tango">

</ul>

</div> <br />
<div class="left column2">
<div>
<% unless @fantweets.nil? || @fantweets.empty? %>
<span style="color:#000;font-weight:bold"> Recent fan replies to all celebs :</span>  <br />
<ul class="divScrollable jcarousel-skin-fan">
<%=  render :partial => "tweets/fanfeed", :locals =>{ :tweets =>  @fantweets ,:url=> fanfeed_tweets_path(:time => @fantweets.to_a.first.time) } %>
</ul>
      <% end %>
</div>
<%=  render :partial => "shared/fb" %>


</div>
<input class="hdnLtstTime" value="<%= Time.now.to_i * 1000 %>" type="hidden" name="" />
</div>
<div class="clr"></div>

</div>
</div>

</div>

<div style="clear:both"></div>